### ISSUE TITLE
[FEATURE] Create initial interface configuration

### ISSUE THREAD

**Issue by Azylog** [h44z/wg-portal#10]
Hello,
Just giving a try to your piece of code ;-) That seems to be really well done, specifically the multiple interfaces support.

In my early start of the container on a test host, the container kept restarting with this error : 
setup failed: unable to setup peer manager: unable to initialize peer manager: failed to get peer list for device wg0: could not get WireGuard device: file does not exist

As it seems you have a 'setup' step in the deployment, could you consider generating a key pair and firing up the interface if it's inexistent ?

That should be much work but I'm not a dev, only a sysadmin and Perl is my last fluent language in date ;-)

As you're commits are quite frequent, I'll probably have a few more features proposals in the next days as my trial goes on (like OIDC).

Thanks again for this works, I'll probably save a project with multi-interface that couldn't be achieved by wg-gen-web.

**Comment by h44z** [comment]
You are right, wg-portal does not handle interface creation. It only works with existing interfaces and can act as configuration helper for those.
The main reason for this is that https://github.com/WireGuard/wgctrl-go, the library that is used to configure the WireGuard interfaces, does not handle creation or deletion of interfaces.

If this feature gets added, it has to be implement in a platform independent way, which might be a bit more work. I am currently not planing to add this  in near future, but I am very happy about contributions or library suggestions for handling the creation/deletion/modification of network interfaces :)

**Comment by Azylog** [comment]
OK, that's probably out of the scope of this project (at least for now) but this could eventually be done with rtnl package : https://pkg.go.dev/github.com/jsimonetti/rtnetlink/rtnl?utm_source=godoc

I can't say neither if this package is OS agnostic nor if it can be used inside a docker container to run interfaces on the host. We probably need the NET_ADMIN capability but this is already mandatory to reconfigure the WG interface.

Let's close this for now, there's better to implement.
