### ISSUE TITLE
Use self generated private key

### ISSUE THREAD

**Issue by SWW13** [h44z/wg-portal#102]
Currently there is no way to create a config without having the client private key on the server, which defeats the purpose of public keys.
I see how this is a sane default for an easy to use configuration interface, however I'd like to have an option for advanced users to provide their own public key instead.

I image this feature to allow users to provide their public key during config creation or update existing configs. This would obviously render the generated config files incomplete, but could be easily circumstanced by using an placeholder like `$PRIVATE_KEY`.

**Comment by h44z** [comment]
in that case simply replace the private key with some placeholder value? 

the placeholder will be included in the generated configs

**Comment by SWW13** [comment]
> in that case simply replace the private key with some placeholder value?

Yes, but the server config needs the public key (which is derived from the private key) so the user has to either supply this during config generation or needs an way to update the public key for existing configs.

**Comment by h44z** [comment]
Leaving the private key empty for peers is no problem. The generated config looks like:

```
....

[Interface]

# Core settings

PrivateKey = <please-insert-your-private-key>

....
```
