### ISSUE TITLE
Pre-shared key (PSK)

### ISSUE THREAD

**Issue by SWW13** [h44z/wg-portal#103]
WireGuard allows the use of an optional pre-shared key for e.g. post-quantum resistance. While not having an PSK currently has no known negative affects on the security it would be a nice and easy future-proof addition. This probably should be optional in wg-portal too.

Pre-shared keys can be generated with `wg genpsk` and need to be set in the server _and_ client config to the _same key_ with `PresharedKey = $PSK`.

**Comment by h44z** [comment]
pre-shared keys are already supported
