### ISSUE TITLE
AllowedIPs not being set at all with v1.0.15

### ISSUE THREAD

**Issue by zyxep** [h44z/wg-portal#108]
Hi,

AllowedIPs is not being set even though there is text in the field in the UI.

**Comment by Dimitrie23** [comment]
Hi, I had this issue as well... If you change the interface config you have to hit the save button on the upper left of the config page. Then it sets the allowedips

**Comment by h44z** [comment]
If you change the default allowed IP's, you have to propagate that change to peers manually by clicking "Apply Global Settings"
