### ISSUE TITLE
Autodetection function

### ISSUE THREAD

**Issue by Logonoff410** [h44z/wg-portal#111]
if you delete the WPC database (`wg_portal.db`), but leave the wg0 file unchanged - containing the parameter `# -WGP- PrivateKey: xxxxx......` then the newly created database does not load this parameter for auto-detected clients, after which it is overwritten, and further connection of this client via `.conf` or QR will not be possible, because the private key will be lost. Please fix it

**Comment by h44z** [comment]
The importer does not parse the wg quick config files, it uses the wgctrl API which does not provide data like peer private keys.
