### ISSUE TITLE
Invalid PrivateKey when user self-provisions via GUI

### ISSUE THREAD

**Issue by kennethdhau** [h44z/wg-portal#112]
Configurations which non-admin users generate (via the GUI, clicking the button in "Open My Profile > [.../peer/create]") have their PrivateKey set to "<please-insert-your-private-key>".

![image](https://user-images.githubusercontent.com/11970451/183308288-fb5c12d9-073c-433c-9091-2c27ea625390.png)

![image](https://user-images.githubusercontent.com/11970451/183308200-622ec366-eacc-45c4-84db-454ed8d9e0b8.png)

Configurations generated through the GUI by an admin user and configurations generated by any user via Swagger are unaffected and valid.

This is present on the latest version published on DockerHub (h44z/wg-portal:latest)

**Comment by l4b4r4b4b4** [comment]
I just recently stumbled over this issue too. Thought I did something wrong. Unfortunately the self provisioning function did not go away, when setting the corresponding ENV variable.

**Comment by mrbanana3000** [comment]
CONFIRMED!
remove line https://github.com/h44z/wg-portal/blob/e6a8e2f2cfe15dcf7d7102510fa7b08572c81f18/internal/server/handlers_peer.go#L426

**Comment by h44z** [comment]
Fixed now. If a user overrides the pre-set public key, the private-key will be removed (as it is not known). Otherwise the private key will stay in the configuration.
