### ISSUE TITLE
LDAP groups to set default wg interface

### ISSUE THREAD

**Issue by Dimitrie23** [h44z/wg-portal#117]
I would like to use this project for an alternative VPN at our university. We are managing our VPN ACLs and vlan access right now with AD groups. So having an option at the environment or the website itself to set default wg interface to a certain LDAP group would be awesome. I'm about to Handle this with a Powershell script and the rest API as a workaround for our managed devices but a more direct implementation would be great so that we can utilize the great provisioning feature for our users. Any chance this is possible?

Best regards,
Dimitrie

**Comment by h44z** [comment]
Currently it is not planned to add a LDAP Group - wg interface binding, but PR are welcome =)
