### ISSUE TITLE
Remove user on LDAP user remove

### ISSUE THREAD

**Issue by vbaidak** [h44z/wg-portal#118]
Hi!

I'm using LDAP for user account sync.
The problem is when the user gets removed from an LDAP it is still present in `Users` in `wg-portal`.
Indeed it is marked as deactivated but how can it be deleted entirely?

Thanks!

**Comment by zyxep** [comment]
If i remember correctly then it's a feature for 2.0 to remove them.
But, I ended up having this in my filter settings:
```
loginFilter: (&(objectClass=organizationalPerson)(mail={{login_identifier}})(!(nsAccountLock=TRUE)))
syncFilter: (&(objectClass=organizationalPerson)(mail=*)(!(nsAccountLock=TRUE)))
```

So if a LDAP user is locked/disabled, the sync will disable it in the portal.

**Comment by vbaidak** [comment]
@zyxep , thanks for adivce!
