### ISSUE TITLE
compile for arm64 does not work

### ISSUE THREAD

**Issue by Alex18081** [h44z/wg-portal#122]
so like the title, arm64 will not compile

cp scripts/wg-portal.service dist
cp scripts/wg-portal.env dist
CGO_ENABLED=1 CC=arm-linux-gnueabi-gcc GOOS=linux GOARCH=arm GOARM=7 go build -ldflags "-linkmode external -extldflags \"-static\" -X github.com/h44z/wg-portal/internal/server.Version=-" -o dist/wg-portal-arm cmd/wg-portal/main.go
-# runtime/cgo
cgo: exec arm-linux-gnueabi-gcc: exec: "arm-linux-gnueabi-gcc": executable file not found in $PATH
make: *** [Makefile:67: dist/wg-portal-arm] Error 2
The command '/bin/sh -c go clean -modcache; go mod tidy; make build-cross-plat' returned a non-zero code: 2

**Comment by h44z** [comment]
you need to install  some dependencies in order to cross-compile this project (as it uses cgo bindings):

````shell
sudo apt-get update

sudo -E apt-get -yq --no-install-suggests --no-install-recommends --force-yes install gcc-arm-linux-gnueabi libc6-dev-armel-cross gcc-arm-linux-gnueabihf libc6-dev-armhf-cross gcc-aarch64-linux-gnu libc6-dev-arm64-cross

sudo ln -s /usr/include/asm-generic /usr/include/asm
````

after that you can run `make build-cross-plat`
