### ISSUE TITLE
Can wg-portal autocreate peers on ldap sync?

### ISSUE THREAD

**Issue by Kokokokoka** [h44z/wg-portal#130]
Hello, this is a great tool, but (as far as I understood) user needs to login and only then wg-peer is generated. It would be great if there is/would be an option to autogenerate peers on ldap sync. Is there such an option?
As a workaround I added CreateUserDefaultPeer to updateLdapUsers ldapsync.go:
```
		if err := s.CreateUserDefaultPeer(user.Email, s.wg.Cfg.GetDefaultDeviceName()); err != nil {
			// Not a fatal error, just log it...
			logrus.Errorf("failed to automatically create vpn peer for %s: %v", user.Email, err)
		}
```

**Comment by h44z** [comment]
There is no such feature right now. Maybe I'll add it to v2. But you can of course create a PR and I will eventually add it to the current version.

**Comment by Kokokokoka** [comment]
Ok,  i'll do the PR then as it looks rather simple.
I've got one more question: (I'll create a separate issue if needed)
I think it would be neat if there would be an option to create certs (when there are multiple interfaced) based on (ldap) groups. what do you think about this?
