### ISSUE TITLE
make build

### ISSUE THREAD

**Issue by x-FBi** [h44z/wg-portal#132]
When you do 'make build' the wg-portal.service looks for wg-portal-amd64, but the script creates wg-portal instead.
I had to nano wg-portal.service and remove -amd64 from the file.  Another solution would be to rename wg-portal, wg-portal-amd64.

Thanks.

**Comment by h44z** [comment]
You can use one of the platform dependent build commands:

- make build-amd64
- make build-arm64
- make build-arm

Those commands generate the executable with a name like wg-portal-[PLATFORM]. 

_make build_ is a generic command that will compile the executable for the platform of the system where make is executed. As this might be an arm or amd64 system the output filename is only wg-portal.

**Comment by x-FBi** [comment]
I understand that you can.  The default is make && make build.  if you do that, your setup breaks.  You MUST enter -amd64 or the like, or it won't work; which all I'm pointing out.

**Comment by x-FBi** [comment]
Advanced commands:
  test-vet             Static code analysis
  test-race            Race condition test
  clean                Delete all generated executables and test files
  build                Build all executables (architecture depends on build system)
  **build                Build all executables for AMD64**  
  build-arm64          Build all executables for ARM64
  build-arm            Build all executables for ARM32
  build-dependencies   Generate the output directory for compiled executables and download dependencies

**Comment by h44z** [comment]
Valid point, I will the makefile
