### ISSUE TITLE
Imposible to Start wg-portal

### ISSUE THREAD

**Issue by alvaroaldama92** [h44z/wg-portal#134]
Hello first of all I want to sorry because I am noob at docker and also sorry for my English.

I am trying to start a new wg-portal container, for that I had read I needed to create first a wg0 interface. For that pupose, I use the next command to start a WireGuard instance:

`
docker run -d \
  --name=wireguard \
  --cap-add=NET_ADMIN \
  --cap-add=SYS_MODULE \
  -e PUID=1000 \
  -e PGID=1000 \
  -e TZ=Europe/London \
  -e SERVERURL=vpn.mydomain.com  \
  -e SERVERPORT=51820  \
  -e PEERS=1  \
  -e PEERDNS=auto  \
  -e INTERNAL_SUBNET=192.168.2.0  \
  -e ALLOWEDIPS=192.168.1.0\24  \
  -e LOG_CONFS=true  \
  -p 51820:51820/udp \
  -v /etc/wireguard:/config \
  -v /lib/modules:/lib/modules  \
  --sysctl="net.ipv4.conf.all.src_valid_mark=1" \
  --restart unless-stopped \
  linuxserver/wireguard
`

With this all seems ok. If I wrote the nest command:
`ls /etc/wireguard/`
I have the next result:
`coredns  peer1  server  templates  wg0.conf`
 Also, if I write:
`docker exec -it wireguard wg show`
I get:

`
interface: wg0
  public key: p4J8oCp75Qsp4J8oCp75Qsp4J8p4J8oCp75Qs=
  private key: (hidden)
  listening port: 51820

peer: p4J8oCp75Qsp4J8oCp75Qsp4J8oCp75Qsp4J8oCp7s=
  preshared key: (hidden)
  allowed ips: 192.168.2.2/32
`

The problem is when I try to start a wg-portal instance. I have the next docker-composer.yaml:
`
version: '3.6'
services:
  wg-portal:
    image: h44z/wg-portal:1.0.6
    container_name: wg-portal
    restart: unless-stopped
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    cap_add:
      - NET_ADMIN
    network_mode: "host"
    volumes:
      - /etc/wireguard:/etc/wireguard
      - ./data:/app/data
    ports:
      - '8123:8123'
    environment:
      - EXTERNAL_URL=http://localhost:8123
      - ADMIN_USER=admin@domain.com
      - ADMIN_PASS=supersecret
      - CONFIG_FILE=/app/config.yml
      - WG_DEVICES=wg0
      - WG_DEFAULT_DEVICE=wg0
      - WG_CONFIG_PATH=/etc/wireguard
      #DB Settings
      - DATABASE_TYPE=mysql
      - DATABASE_HOST=192.168.1.20
      - DATABASE_PORT=3306
      - DATABASE_NAME=wg_db
      - DATABASE_USERNAME=wg_user
      - DATABASE_PASSWORD=wg_pass
`
then I execute:
`docker-compose up -d`

If I search into the log of wg-portal, and I always have the same errors in loop:
`FATA[2022-12-10 20:00:46] setup failed: unable to setup peer manager: unable to initialize peer manager: failed to get peer list for device wg0: could not get WireGuard device: file does not exist 
INFO[2022-12-10 20:00:46] starting WireGuard Portal Server [unknown (local build)]... 
INFO[2022-12-10 20:00:46] real working directory: /app                 
WARN[2022-12-10 20:00:46] unable to load config.yml file: failed to open config file /app/config.yml: open /app/config.yml: no such file or directory, using default configuration... 
INFO[2022-12-10 20:00:46] current working directory: `

I think I tried to find the solution in all isues of the post, but nothing works.

Thanks in advance

**Comment by jonston1corporated** [comment]
У меня такая же проблема.

**Comment by h44z** [comment]
if you run `ip link show` on the host system (not inside a container), does it show the wg0 interface?

**Comment by alvaroaldama92** [comment]
I think not:
`root@docker ~# ip link show`

`1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN mode DEFAULT group default qlen 1000 link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00`
`2: eth0@if25: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP mode DEFAULT group default qlen 1000 link/ether 8a:ab:d5:e0:d0:8a brd ff:ff:ff:ff:ff:ff link-netnsid 0`
`3: br-1c8d4ff40714: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN mode DEFAULT group default link/ether 02:42:0e:af:5e:c0 brd ff:ff:ff:ff:ff:ff`
`4: br-1d4789e970f6: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN mode DEFAULT group default link/ether 02:42:d0:cb:72:2b brd ff:ff:ff:ff:ff:ff`
`5: docker0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP mode DEFAULT group default link/ether 02:42:2f:ef:3f:67 brd ff:ff:ff:ff:ff:ff`
`7: veth3105349@if6: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master docker0 state UP mode DEFAULT group default link/ether 06:1d:54:6f:43:ee brd ff:ff:ff:ff:ff:ff link-netnsid 1`
`53: vethee520bd@if52: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master docker0 state UP mode DEFAULT group default  link/ether ea:2d:e0:72:02:dc brd ff:ff:ff:ff:ff:ff link-netnsid 2`

**Comment by h44z** [comment]
Ok, the linuxserver/wireguard container does not expose the WireGuard interface. So no other container can access it by default.

You can move the WireGuard container to the host network, then the interface is also visible on the host system. The 
WireGuard Portal container can also access the interface because it is running in host-network mode by default.

```
docker run -d \
 --name=wireguard \
 --cap-add=NET_ADMIN \
 --cap-add=SYS_MODULE \
 --network host \
 -e PUID=1000 \
 -e PGID=1000 \
 -e TZ=Europe/London \
 -e SERVERURL=vpn.mydomain.com  \
 -e SERVERPORT=51820  \
 -e PEERS=1  \
 -e PEERDNS=auto  \
 -e INTERNAL_SUBNET=192.168.2.0  \
 -e ALLOWEDIPS=192.168.1.0\24  \
 -e LOG_CONFS=true  \
 -v /etc/wireguard:/config \
 -v /lib/modules:/lib/modules  \
 --restart unless-stopped \
 linuxserver/wireguard
```
