### ISSUE TITLE
Sign in as user with uppercase letter fails

### ISSUE THREAD

**Issue by KSebion** [h44z/wg-portal#14]
I had problems signing in with multiple different users that each had an uppercase character.
I discovered that I did not have problems when the characters were all lower case.
The following links may be related.

https://github.com/h44z/wg-portal/blob/926733dea49d64072ecddf67fd18d19ff4804a06/internal/authentication/providers/password/provider.go#L58
https://github.com/h44z/wg-portal/blob/926733dea49d64072ecddf67fd18d19ff4804a06/internal/users/manager.go#L97
https://github.com/h44z/wg-portal/blob/926733dea49d64072ecddf67fd18d19ff4804a06/internal/users/manager.go#L100

**Comment by h44z** [comment]
I assume you have created the users with an uppercase email address right?

**Comment by KSebion** [comment]
Yes.

**Comment by h44z** [comment]
This issue should now be fixed. All email addresses now are mapped to lower case. Existing email addresses in the database will automatically be transformed to lower case.
You can test the changes by using the latest docker image. I will create a new tagged release soon.

**Comment by KSebion** [comment]
Nice. Thanks!
