### ISSUE TITLE
Applying global Client Settings looses the Server Settings

### ISSUE THREAD

**Issue by gudata** [h44z/wg-portal#141]
Hello,
I go to "Server Mode" and enter values in those fields:

Listen Port, Public Endpoint for Clients

Then I go to "Client Mode" and press the "Save" button,
the fields "Listen Port, Public Endpoint for Clients" from "Server Mode" are blank.

**Comment by rlowevoiply** [comment]
i have this issue as well

**Comment by h44z** [comment]
this works as intended. for client mode it is not possible to set the port for example

**Comment by gudata** [comment]
It is an UI issue where the values are deleted on "Save" Instead of keeping them.
