### ISSUE TITLE
Is healtcheck listening on all interfaces?

### ISSUE THREAD

**Issue by gudata** [h44z/wg-portal#144]
Hello,
When I do nestat I see 
```
tcp6       0      0 :::11223                :::*                    LISTEN      3314250/wg-portal-a
```
Does it means that it listen on all interfaces? I saw in the code you are saynig 127.0.0.1.

How to disable/change port/interface on that service?

I personally don't see any need to having additional port used in case we have the web interface port and the health check can be served from there.

**Comment by h44z** [comment]
Which version are you using? Master and 1.0.16 give me:

`tcp        0      0 127.0.0.1:11223         0.0.0.0:*               LISTEN      0          235286     -`
