### ISSUE TITLE
No more available address from cidr

### ISSUE THREAD

**Issue by aerscs** [h44z/wg-portal#147]
When I click on a "Add a peer" button in the administration panel, an error "500 Session error" appears. It says 
> failed to prepare new peer: failed to get available IP addresses: no more available address from cidr
If I add multiple peers, the error is still there. Any ideas how to fix this?

My server's interface configuration: 
Listen port - 51820
Server IP address - 10.50.0.1/32

Global client configuration:
Public Endpoint for clients - (host-ip):51820
Default allowed IPs - 0.0.0.0/0
Persistent Keepalive - 25

**Comment by h44z** [comment]
Server IP address - 10.50.0.1**/32**   - with /32 you only get one IP address. Maybe change that to /24?

**Comment by aerscs** [comment]
> Server IP address - 10.50.0.1**/32** - with /32 you only get one IP address. Maybe change that to /24?

That worked! Thank you so much! <3
