### ISSUE TITLE
How to get logs (where i should find them) ?

### ISSUE THREAD

**Issue by vskubriev** [h44z/wg-portal#15]
Despite additional option like `LOG_LEVEL=debug` applied from compose there is no logs in:

1. `compose up cmd`
2. docker logs wg-portal
3. some file in running container (at least i couldn't find it)

But code already has logging (i saw inside the code).

So the issue is that documentation does not cover debugging a lots.

**Comment by h44z** [comment]
The logs are written to stdout. So they are visible in docker-compose logs (or docker logs).
If they are not visible, you might have changed the logging settings of your docker setup.

**Comment by vskubriev** [comment]
Already done. But unfortunately debug logs is absent.
