### ISSUE TITLE
LDAP Disabling/Enabling user problem. UNIQUE constraint failed

### ISSUE THREAD

**Issue by Alexander-Kazandzhiyan** [h44z/wg-portal#150]
Hello.
1. Portal starting with auth in LDAP (freeipa) and user **testwebportalwireguard@mydomen.com** can to login into portal.
2. then i Open LDAP and disable user **testwebportalwireguard@mydomen.com**
3. In portal user management user **testwebportalwireguard@mydomen.com** now RED. And he cant to login.
4. Open LDAP and enable user **testwebportalwireguard@mydomen.com**
5. In portal user management user **testwebportalwireguard@mydomen.com** stay in RED color. And he cant to login.
in logs i see 2 message every 1 minute:
```
wg-portal    | DEBU[2023-02-06 15:05:56] updating ldap user testwebportalwireguard@mydomen.com
wg-portal    | ERRO[2023-02-06 15:05:56] failed to update ldap user testwebportalwireguard@mydomen.com in database: failed to update user testwebportalwireguard@mydomen.com: UNIQUE constraint failed: users.email
```
7. in sqlite in user table i see record of this user with date of deletion in last column:
```
testwebportalwireguard@mydomen.com|ldap|0|testwebportalwireguard|testwebportalwireguard|||2023-02-03_14:12:34.084386182+00:00|2023-02-03_14:12:34.089895269+00:00|2023-02-06_14:08:43.148759028+00:00
```
8.  it means that the user still in DB and cant to be added ones more. But now he dont disabled in LDAP and he must to start to login to portal. But he cant with the error:

```
500
login error
failed to update user data: failed to update user in manager: failed to update user testwebportalwireguard@mydomen.com: UNIQUE constraint failed: users.email
```
10. If i delete string of this user from db, after 1 min user can to login. Because user successfully synchronize from LDAP.

I dont understand how it must to work if user is not delete from LDAP, but must be temporary disabled and enabled. (without manual deletion row from db)
i hope you understand my situation and question.

**Comment by Alexander-Kazandzhiyan** [comment]
i solve myself.
in filter 
- LDAP_SYNC_FILTER=(&(objectClass=organizationalPerson)(memberof=cn=vpnusers,cn=groups,cn=accounts,dc=mydomain,dc=com)(!(nsaccountlock=TRUE)))
i just remove (!(nsaccountlock=TRUE))

**Comment by sentoz** [comment]
Hello,

Your solution is not a bug fix.
Might be worth opening issue

**Comment by commonism** [comment]
Please re-open - gorm (v2) Save is not meant to be used as UPSERT any longer

https://github.com/go-gorm/gorm/issues/3568
