### ISSUE TITLE
cpu oveload after peer over 200

### ISSUE THREAD

**Issue by gbt780** [h44z/wg-portal#151]
hi cpu load very high after number of peers over 200 can you help me ?

**Comment by h44z** [comment]
hi, this is due to the ping checks for each peer. Currently there is no easy way to disable this, but it will be improved in v2.

**Comment by mzs114** [comment]
> hi, this is due to the ping checks for each peer. Currently there is no easy way to disable this, but it will be improved in v2.

Hi, is it possible to disable the pings and have around 2000 peers? Or will be be toggle option or improved in the upcoming one?
