### ISSUE TITLE
Allocating different subnets

### ISSUE THREAD

**Issue by Smiley-k** [h44z/wg-portal#157]
Is it possible to integrate with active directory to give out different networks with different access to servers based on the user's belonging to the active directory group?

For example Group in AD 
VPN-analytics-access - 10.0.0.0/24
VPN-RDP-access- 10.10.10.0/24
VPN-WEB-portal - 10.20.20.0/24

respectively users to access their network with access to the necessary resources.

**Comment by bonddim** [comment]
Closing as duplicate #136
