### ISSUE TITLE
HTTPS for the application

### ISSUE THREAD

**Issue by halpro** [h44z/wg-portal#158]
Hello,
Does anyone mind if I will add the HTTPS option to the application? I have seen several same suggestions and I agree that plain insecure HTTP mode for the app is not good at all if anyone will expose the app to the world.
See https://medium.com/rungo/secure-https-servers-in-go-a783008b36da

**Comment by philippderdiedas** [comment]
Isn't state of the art to use a reverse Proxy?
E.g. [Nginx Proxy Manager](https://nginxproxymanager.com/)

**Comment by h44z** [comment]
you have to use a reverse proxy for https
