### ISSUE TITLE
API - Peers.DeviceType is "" when listing via GetPeers

### ISSUE THREAD

**Issue by commonism** [h44z/wg-portal#170]
Hi,

due to the changes in https://github.com/h44z/wg-portal/pull/127 / https://github.com/h44z/wg-portal/pull/127/commits/0f338718506040fd2cba4e53726158f874d67c46 

https://github.com/h44z/wg-portal/blob/b3a5f2ac607251bd9eacca28f3dfa5b245bb29c6/internal/server/docs/docs.go#L1452-L1458

the protocol mismatches the description document as the DeviceType is "" when listing peers via GetPeers.

**Comment by h44z** [comment]
fixed in 1.0.19

**Comment by h44z** [comment]
Please make sure to update the Docker image from **h44z/wg-portal** to **wgportal/wg-portal**.
