### ISSUE TITLE
Please use v2 branch for alpha code

### ISSUE THREAD

**Issue by paulignari** [h44z/wg-portal#173]
This is more a wish than a bug, but using master for alpha code can break automated procedures and is prone to errors despite the warning about using a stable version.

I notice that you have already created a v2 branch, why not use it for alpha/beta development  merging it in master when ready?

It may be more gentle for users and simple for you, if a need for a version 1.0.19 will raise tomorrow...

Thanks.

Paolo

**Comment by v3nko** [comment]
Also, having a `stable` tag for the Docker image would be helpful, so that users can avoid any potential issues with the `latest` tag.

**Comment by h44z** [comment]
I will add a stable tag soon. 
In general it is never a good idea to use the lastest tag for Docker containers.

**Comment by h44z** [comment]
There now exists a **[stable](https://github.com/h44z/wg-portal/tree/stable)** branch where the current stable version (in this case v1) is developed. 

The master branch is used for new developments and might contain unstable code.


## New Docker Images
The Docker-Hub repository was moved to an organization: [**wgportal/wg-portal**](https://hub.docker.com/r/wgportal/wg-portal).
Please update all old image references from **h44z/wg-portal** to **wgportal/wg-portal**.

The Docker version schema was also adopted. There are the following new tags:

- **latest**: The latest build from the **master** branch. Not a stable tag!
- **master**: same as latest
- **stable**: The latest build from the **stable** branch.
- **v1**: The latest version of WireGuard Portal V1 
- **v2**: The latest version of WireGuard Portal V2
- **major.minor**: Latest x.y version (available for v1 and v2)
- **major.minor.patch**: Exact x.y.z version, corresponding to the Git tag (available for v1 and v2)
