### ISSUE TITLE
Is adding a Chinese translation in the project's V2 version plan possible? 

### ISSUE THREAD

**Issue by soloradish** [h44z/wg-portal#176]
If it is, I'm willing to try adding a Simplified Chinese translation file.

**Comment by h44z** [comment]
This should be rather simple. Just add the new language here: https://github.com/h44z/wg-portal/tree/master/frontend/src/lang and add a language flag to https://github.com/h44z/wg-portal/blob/master/frontend/src/App.vue

**Comment by soloradish** [comment]
Got it. I will reopen this issue when my PR is ready. Thank you

**Comment by ClarkQAQ** [comment]
> Got it. I will reopen this issue when my PR is ready. Thank you

#316 I have added the basic Chinese translation. If there are no issues, it can be used directly.
