### ISSUE TITLE
QR size limited for long IP ranges

### ISSUE THREAD

**Issue by TheOneWithTheBraid** [h44z/wg-portal#18]
For our setup, we have very difficult IP ranges we provide (Allowed IPs). In some cases, they consist of more than 50 different IP blocks we provide in the config. If we do this, the QR codes are no longer displayed, even though `qrencode -t ansiutf8 < myconfig.conf` properly works for importing the profiles.

**Comment by TheOneWithTheBraid** [comment]
Okay, we workarounded this by shrinking the number of IP blocks we require.

**Comment by TheOneWithTheBraid** [comment]
Yes seems so. I'm just wondering why the terminal command reaches at encoding the data. Maybe due to a different error correction?

But I don't mind, we workarounded this by shrinking the data.

**Comment by h44z** [comment]
WireGuard Portal uses medium error correction (M), I will change that to low error correction if the configuration data is too long.
With low error correction we can store 2956 bytes, but if that size is exceeded it is not possible to create the QR code.

**Comment by h44z** [comment]
If the size exceeds the limit of medium error correction, low error correction will be used. So there is more space available in the QR-code. Even though, at some point a limit is reached which we can not avoid.
