### ISSUE TITLE
Auto IP for new peer odd

### ISSUE THREAD

**Issue by denser** [h44z/wg-portal#185]
I get wg default peer ip network 10.1.1.0/24
wg ip 10.1.1.1/24

When i press create peer form shows up and suggest me to use 10.1.1.2/32
kk i agreed.
Create next - form shows up and again - 10.1.1.2/32 as new peer ip.
Canceling. Go to first peer settings and change from 10.1.1.2/32 to 10.1.1.2/24

And now press create new peer and now suggesting 10.1.1.3/32

Seems to me algorithm for new IP for peer need to be modified.

**Comment by h44z** [comment]
fixed
