### ISSUE TITLE
Can't grant admin's rights via ldap to group users

### ISSUE THREAD

**Issue by Sarevok933219** [h44z/wg-portal#187]
Good day. I have added ldap user mapping using docker compose environment. My env is:
      - LDAP_BASEDN=ou=users,dc=mydomain,dc=ru
      - LDAP_USER=cn=admin,dc=mydomain,dc=ru
      - LDAP_ADMIN_GROUP=cn=wg_admins,ou=Admins_groups,dc=mydomain,dc=ru
      - LDAP_LOGIN_FILTER=(&(objectClass=person)(uid={{login_identifier}}))
      - LDAP_SYNC_FILTER=(objectClass=person)
      - LDAP_ATTR_GROUPS=memberUid
      - LDAP_TYPE=OpenLDAP
I have success list of users, but no attribute is_admin detected. Logs logs broadcast info what no groups matched. We do not have a memberUid in the ldap scheme and there is no technical possibility to add it. We want to use as an admin regular group (cn=wg_admins,ou=Admins_groups,dc=mydomen,dc=ru) with the memberUid attribute where the participants that are contained in it and must have admin's permissions. Please give any example to implement this case.

**Comment by h44z** [comment]
there is no way if the groups are not listed in the user record.

The check is implemented like this:

```go
for _, group := range sr.Entries[0].GetAttributeValues(provider.config.GroupMemberAttribute) {
  if group == provider.config.AdminLdapGroup {
    user.IsAdmin = true
    break
  }
}
```

So the value of LDAP_ADMIN_GROUP has to be contained in the group list (retrieved from the value LDAP_ATTR_GROUPS)
