### ISSUE TITLE
Migrate to another server?

### ISSUE THREAD

**Issue by rlowevoiply** [h44z/wg-portal#188]
Is is possible to migrate this setup from one server to another, if so what all needs to be moved over?

**Comment by h44z** [comment]
Sure, but it depends on your setup.

If you use Docker, simply copy your docker-compose.yml, your database and config files to the new server. Also copy the /etc/wireguard directory.
Make sure that WireGuard is installed on the new server and start up the Docker container again.

For non-dockerized setups, simply copy the wg-portal application files, database and config files as well as /etc/wireguard.
