### ISSUE TITLE
Peer view broken for non admin users V2

### ISSUE THREAD

**Issue by ebakoba** [h44z/wg-portal#196]
Working path:

1. I login in as an admin user
2. I re-login as a regular user
3. I look at my profiles and can see the profile
4. Clicking on the eye icon opens up the peer configuration

Broken path:
1. I login in as a regular user (using incognito for no cache)
2. The peer is displayed in the list
3. Clicking on the eye icon does not open the peer configuration. Instead an empty modal is shown:

![image](https://github.com/h44z/wg-portal/assets/14753019/9a54c871-9a8c-4715-909b-b0d68b3051c1)

It seems like there is a request for the said configuration, but it incorrectly does not include the `Identifier`:

![image](https://github.com/h44z/wg-portal/assets/14753019/b3d56fd5-50f0-4b3d-8c23-26ce02422878)

**Comment by h44z** [comment]
should be solved now
