### ISSUE TITLE
docker: failed to load config from yaml: open config/config.yml: no such file or directory

### ISSUE THREAD

**Issue by RogerSik** [h44z/wg-portal#197]
When creating a fresh wg-portal container (with wgportal/wg-portal:2.0.0-alpha.1) the container crashes with
```
panic: failed to load config from yaml: open config/config.yml: no such file or directory
```

do i need to create this file before? I thougt because of the environmental variables that this file will get to be created from docker container?

**Comment by h44z** [comment]
The file is not created automatically. You should use a docker volume on /app/config which contains the config.yml file.
