### ISSUE TITLE
multiple interface support

### ISSUE THREAD

**Issue by DJSundog** [h44z/wg-portal#2]
Thanks for this project, it's very nice!

Is it possible to manage multiple wgN.conf interfaces?

I am setting up wg0 with peers on my local network but a number of peer connections to other public endpoints via wg1, wg2, etc. and would love to be able to manage those configurations via the same web interface as my local peers.

**Comment by h44z** [comment]
Multiple interfaces are now supported. It is also supported to have "client" and "server" interfaces.

**Comment by DJSundog** [comment]
Awesome - thanks so much!!
