### ISSUE TITLE
[feature-request] Allow profile creation as self service

### ISSUE THREAD

**Issue by TheOneWithTheBraid** [h44z/wg-portal#20]
For our use case, we would like to allow normal users to create their own VPN profiles.

We imagine of the following options
- an admin option to enable the whole self-service
- self-service profiles always use the inherited global settings
- option to limit number of self-service profiles

In this case, admins are only responsible for managing *special* profiles.

---

An alternative we imagine of is one automatically created default profile per user.

**Comment by h44z** [comment]
Creation of a default profile on first login is already possible. See **CREATE_DEFAULT_PEER** config option.

**Comment by h44z** [comment]
This will not be implemented at the moment, maybe in the future ...
