### ISSUE TITLE
What makes the naming of peers configuration?

### ISSUE THREAD

**Issue by MaxSonicDev** [h44z/wg-portal#204]
Hello, 

Some information about my setup for wg-portal :

OS : Alma Linux 9
Package : build by myself run into systemd service
User : based on active directory, sync with ldap protocol
Version use : Actual Stable v1.0.19

I'm looking for a way to modify wg-portal to make a personal version that meets an automation problem. 

When I download a file containing special characters, I get this

Surname : Dubois
First name: Éric
Client Friendly Name: Default

The expected file: Eric-Dubois-Default.conf
The file with the current stable version: ric-Dubois-Default.conf 

I would like to know if it is possible to explain me which line of code manages the download part so that I can modify it for a personal version where I can replace the accent instead of just deleting them. 

PS : Yes i know, it's a french problem :')

**Comment by h44z** [comment]
Hi,

as I had problems with filenames on windows, thus all special  characters (everything except a-z A-Z 0-9 - and _) are stripped away. The filename is also limited to 16 characters.

The function can be seen here: https://github.com/h44z/wg-portal/blob/master/internal/domain/peer.go#L86

Improvements are always welcome =)
