### ISSUE TITLE
Secufity: Non-admin users can get all the sensitive information.

### ISSUE THREAD

**Issue by ReeseWang** [h44z/wg-portal#209]
Version: Current master branch

Reproduce steps:

1. Create a non-admin user.
2. Login as that user with a browser.
3. Access http[s]://ip[:port]/api/v0/interface/all with that browser. You can get the private key of WireGuard interface.

I've also tried /api/v0/user/all endpoint and /api/v0/user/<userid>/peers endpoint, both can be accessed by non-admin users.

**Comment by h44z** [comment]
nice catch, should be fixed now
