### ISSUE TITLE
WARN[2024-02-05 13:36:52] unable to load config.yml file: failed to open config file "/app/config/config.yml": open "/app/config/config.yml": no such file or directory, using default configuration...

### ISSUE THREAD

**Issue by NerijusIPR** [h44z/wg-portal#212]
Hi,

I cant bypass error with config.yml file.

Docker-compose:

> version: '3.6'
> services:
>   wg-portal:
>     image: wgportal/wg-portal:stable
>     restart: unless-stopped
>     cap_add:
>       - NET_ADMIN
>     network_mode: "host"
>     ports:
>       - "8888:8888"
>     volumes:
>       - /etc/wireguard:/etc/wireguard
>       - ./data:/app/data
>       - ./config:/app/config
>     environment:
>       - CONFIG_FILE="/app/config/config.yml

      
 Directory structure:
 

> root@testst:/opt/wgportal# ls -la
> drwxr-xr-x 4 root root 4096 Feb  5 13:36 .
> drwxr-xr-x 5 root root 4096 Feb  5 09:40 ..
> drwxr-xr-x 2 root root 4096 Feb  5 13:19 config
> drwxr-xr-x 2 root root 4096 Feb  5 13:36 data
> -rw-r--r-- 1 root root  357 Feb  5 13:36 docker-compose.yaml
> 
> root@trstt:/opt/wgportal# ls -la config/config.yml 
> -rw-r--r-- 1 root root 473 Feb  5 13:19 config/config.yml

error:

> wg-portal_1  | INFO[2024-02-05 13:38:46] sysinfo: os=linux, arch=amd64                
> wg-portal_1  | INFO[2024-02-05 13:38:46] starting WireGuard Portal Server [stable-e6b01a9]... 
> wg-portal_1  | INFO[2024-02-05 13:38:46] real working directory: /app                 
> wg-portal_1  | INFO[2024-02-05 13:38:46] current working directory: .                 
> **wg-portal_1  | WARN[2024-02-05 13:38:46] unable to load config.yml file: failed to open config file "/app/config/config.yml": open "/app/config/config.yml": no such file or directory, using default configuration...** 
> wg-portal_1  | #############################################
> wg-portal_1  | Administrator credentials:
> wg-portal_1  |   Email:     admin@wgportal.local
> wg-portal_1  |   Password:  sgfdfgdfgdfgdf
> wg-portal_1  | 
> wg-portal_1  | This information will only be displayed once!
> wg-portal_1  | #############################################
> wg-portal_1  | INFO[2024-02-05 13:38:46] setup of service completed!                  
> wg-portal_1  | INFO[2024-02-05 13:38:46] starting web service on :8123

version: stable-e6b01a9

**Comment by Bhargav79** [comment]
Same issue here

**Comment by vbaidak** [comment]
I think this is because you are trying to use **wg-portal v1** docker image. You should switch to [v1](https://github.com/h44z/wg-portal/tree/stable) project and its configuration in that case, otherwise upgrade the version to **v2+**
See the **IMPORTANT** note at the top of the README

**Comment by h44z** [comment]
I cannot reproduce this problem for v1 either, my working example:

```
user@SERVER:/srv/wireguard_v1$ ls -la
total 44
drwxrwxr-x+  5 root root  4096  Apr  2  21:20 .
drwxr-xr-x+ 13 root root  4096  Apr  1  22:40 ..
drwxrwxr-x+  2 root root  4096  Apr  2  21:20 config
drwxr-xr-x+  2 root root  4096  Aug  5  2023  data
-rw-rw-r--+  1 root root  1212  Apr  2  21:19 docker-compose.yml

user@SERVER:/srv/wireguard_v1$ ls -la config/
total 12
drwxrwxr-x+ 2 root  root       4096 Apr  2 21:20 .
drwxrwxr-x+ 5 root  root       4096 Apr  2 21:20 ..
-rw-rw-r--+ 1 root  root         32 Apr  2 21:20 config.yml

user@SERVER:/srv/wireguard_v1$ cat docker-compose.yml 
version: '3.6'
services:
  wg-portal:
    image: wgportal/wg-portal:stable
    container_name: wg-portal
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    network_mode: "host"
    volumes:
      - /etc/wireguard:/etc/wireguard
      - ./data:/app/data
      - ./config:/app/config
    environment:
      # WireGuard Settings
      # ...
      # Misc Settings
      - LOG_JSON=false
      - LOG_LEVEL=trace
      - CONFIG_FILE=/app/config/config.yml
```

maybe your environment variable CONFIG_FILE is incorrect? I can see invalid quotes (")...
