### ISSUE TITLE
db migration error

### ISSUE THREAD

**Issue by johnjeffers** [h44z/wg-portal#23]
Getting the following error when trying to start with wg-portal pointed at a mysql database (new, empty RDS instance):

```
setup failed: unable to setup peer manager: failed to migrate peer database: Error 1822: Failed to add the foreign key constraint. Missing index for constraint 'fk_peers_device' in the referenced table 'peers'
```

Any suggestions on how to fix that?

**Comment by johnjeffers** [comment]
Never mind that. I just dropped and recreated the database, and I'm not getting that error anymore.

Unfortunately, I'm getting this one instead:

```
setup failed: unable to setup peer manager: unable to initialize peer manager: failed to validate device wg0: failed to create autodetected device: Error 1452: Cannot add or update a child row: a foreign key constraint fails (`wg_portal`.`devices`, CONSTRAINT `fk_peers_device` FOREIGN KEY (`device_name`) REFERENCES `peers` (`public_key`))
```

The exact same config works fine using local sqlite, so I'm not sure what's different with mysql.

**Comment by h44z** [comment]
@johnjeffers the problem should be fixed (testable with the latest docker image)

**Comment by johnjeffers** [comment]
@h44z thank you! I'll try to test it in the next day or two.

**Comment by johnjeffers** [comment]
@h44z it worked! thanks!!
