### ISSUE TITLE
Expose the app in port 443 (HTTPs)

### ISSUE THREAD

**Issue by rquintanab** [h44z/wg-portal#240]
Hello,

I would like to know if it's possible to expose the application on port 443 (HTTPS) and be able to load SSL certificates. This way, Google would recognize my application as secure and allow logging in through Google. If the application is exposed on port 8888, Google tells me that it cannot trust the application and therefore does not allow logging in.
If it is possible, how should I do it?

**Comment by h44z** [comment]
you can now also specify **cert_file** and **key_file** variables to expose HTTPS directly
