### ISSUE TITLE
Wireguard Configuration files

### ISSUE THREAD

**Issue by lks-rablanco** [h44z/wg-portal#247]
Good afternoon,
I have searched the docker instance with shell and have not found any config file regarding interface configuration , where is this configuration stored? is there another place outside of the db where this is stored?
also, is there a way to make another admin user?

**Comment by bonddim** [comment]
They are generated after creating interface in the UI

**Comment by lks-rablanco** [comment]
I have checked etc/wirguard and there is no config file there
