### ISSUE TITLE
overwriting the etc/wireguard/wg0.conf file on peer creation

### ISSUE THREAD

**Issue by lks-rablanco** [h44z/wg-portal#249]
is there a way for the app to overwrite the wg0.conf file automatically? if not, I think this is a bug because the changes are not reflected on the file and the wgservice is not getting restarted after an user is created

**Comment by kazantsev-dmitry** [comment]
you can add "config_storage_path" to your config.yml, then you can save the wg0.conf file by clicking on the save button in the web interface
```
advanced:
  config_storage_path: /etc/wireguard/
```
