### ISSUE TITLE
Need a help with starting wg-portal

### ISSUE THREAD

**Issue by SMILE009** [h44z/wg-portal#25]
Hello first of all thank you for you solution. Great work

I am trying to spin up composer
compose.yml from example

`version: '3.6'
services:
  wg-portal:
    image: h44z/wg-portal:latest
    container_name: wg-portal
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    network_mode: "host"
    volumes:
      - ./wireguard:/etc/wireguard
      - ./data:/app/data
    environment:
      # WireGuard Settings
      - WG_DEVICES=wg0
      - WG_DEFAULT_DEVICE=wg0
      - WG_CONFIG_PATH=/etc/wireguard
      # Core Settings
      - EXTERNAL_URL=https://vpn.company.com
      - WEBSITE_TITLE=WireGuard VPN
      - COMPANY_NAME=Your Company Name
      - ADMIN_USER=admin@domain.com
      - ADMIN_PASS=supersecret
      # Mail Settings
      - MAIL_FROM=WireGuard VPN <noreply+wireguard@company.com>
      - EMAIL_HOST=10.10.10.10
      - EMAIL_PORT=25
      # LDAP Settings
      - LDAP_ENABLED=false
      - LDAP_URL=ldap://srv-ad01.company.local:389
      - LDAP_BASEDN=DC=COMPANY,DC=LOCAL
      - LDAP_USER=ldap_wireguard@company.local
      - LDAP_PASSWORD=supersecretldappassword
      - LDAP_ADMIN_GROUP=CN=WireGuardAdmins,OU=Users,DC=COMPANY,DC=LOCAL`
      
  I got error 
  
`$ docker-compose up
Creating wg-portal ... done
Attaching to wg-portal
wg-portal    | INFO[2021-06-17 10:38:46] starting WireGuard Portal Server [latest-92d0953]... 
wg-portal    | INFO[2021-06-17 10:38:46] real working directory: /app                 
wg-portal    | INFO[2021-06-17 10:38:46] current working directory: .                 
wg-portal    | WARN[2021-06-17 10:38:46] unable to load config.yml file: failed to open config file config.yml: open config.yml: no such file or directory, using default configuration... 
wg-portal    | FATA[2021-06-17 10:38:46] setup failed: unable to setup peer manager: unable to initialize peer manager: failed to get peer list for device wg0: could not get WireGuard device: file does not exist `

The same error I got when I am trying to spin up it on k8s cluster

**Comment by h44z** [comment]
Hi,

does your host have a wireguard interface wg0 enabled/configured? WireGuard Portal only serves as a configuration tool for existing interfaces, it cannot create WireGuard interfaces nor does it contain WireGuard in the docker image.
