### ISSUE TITLE
Client Peers DNS servers not apply into the configuration

### ISSUE THREAD

**Issue by SealinGp** [h44z/wg-portal#252]
1. click 'setting' icon and edit the vpn peers and write "DNS server", but it didn't apply to to configuration
<img width="1781" alt="image" src="https://github.com/h44z/wg-portal/assets/32982627/bf8393a2-fe51-4a72-9ec0-f9f5f2ed5eae">

2. click 'eye' icon and review the configurations
<img width="894" alt="image" src="https://github.com/h44z/wg-portal/assets/32982627/175998b5-6640-4308-bd12-6e6a10c8e848">

**Comment by eforemny** [comment]
press "enter" after you set the ip while still in the field. the ip should switch to the "blue" layout

**Comment by SealinGp** [comment]
> press "enter" after you set the ip while still in the field. the ip should switch to the "blue" layout

got it. thanks so much
