### ISSUE TITLE
/bin/sh does not exist

### ISSUE THREAD

**Issue by xphil-22** [h44z/wg-portal#253]
Hello I encountered an issue in the v1 stable version of the wg-portal. It seems that the v1 docker image doesn't have a /bin/sh. I need that in in my Docker Container to do some extra additions (install dependencies with RUN in the docker file). I solved it by forcing your repo and editing the Dockerfile of the original stable image and compiled it by myself. What I exactly did was replacing the "From scratch" to "From alpine:1.19.3" because scratch doesn't have a /bin/bash. This solves my error. Is there any reason why it is extending from scratch? Is it possible to replace this also in the stable version?

**Comment by h44z** [comment]
This was changed with v2. If you need it in v1, please create your own Docker image
