### ISSUE TITLE
ldap autocompletion and pressing enter on "create new clients" causes the creation of two email addresses

### ISSUE THREAD

**Issue by pedro-nonfree** [h44z/wg-portal#27]
![image](https://user-images.githubusercontent.com/39959198/123156523-b055ce00-d469-11eb-9ab0-6334944054fa.png)

when I press enter this is what happens:

![image](https://user-images.githubusercontent.com/39959198/123436799-4ce5b080-d5cf-11eb-85f7-da744430a851.png)

if I press enter again, it creates two accounts

```
Jun 23 19:29:57 cdist-t1 wgportal[20418]: INFO[2021-06-23 19:29:57] creating 2 ldap peers
```

**Comment by h44z** [comment]
Fixed in the new release
