### ISSUE TITLE
Redirect traffic to domain

### ISSUE THREAD

**Issue by Sarevok933219** [h44z/wg-portal#276]
Hello. Please tell, is there any way to redirect traffic to domain (not IPs), using WG-Portal? Field "Allowed IPs" provides the ability to manage only IP addresses.
![image](https://github.com/h44z/wg-portal/assets/56883129/0842785d-142a-400a-bc8f-b9679ea37465)

**Comment by h44z** [comment]
I don't know of any easy way to do domain-based routing.
