### ISSUE TITLE
Option to bind webserver to specific interface

### ISSUE THREAD

**Issue by gq97a6** [h44z/wg-portal#277]
It would be great to see a option to bind the webserver to specific interface. As this container runs with **network_mode: host** there is no option to bind it to for example to 10.8.0.1 with docker ports config. Currently the only way to prevent public access is through firewall rules. Maybe split the application into two containers, one for the core and one for the web, which would not have to use **network_mode: host**.

**Comment by bonddim** [comment]
@gq97a6, did you tried to set
```yaml
web:
  listening_address: 10.8.0.1:8888
```
as mentioned in [configuration-options](readme-ov-file#configuration-options) ?
