### ISSUE TITLE
when not pressing enter on "create new clients" creates nothing

### ISSUE THREAD

**Issue by pedro-nonfree** [h44z/wg-portal#28]
If I feel email address and then click Create, it does not do anything

![image](https://user-images.githubusercontent.com/39959198/123157438-d4fe7580-d46a-11eb-97fb-5d96e86a490d.png)

if focus is no where or in client friendly name it does nothing

only when focus is in email address field, it "squares" the address and with another enter creates the client "client(s) created succesfully"

**Comment by h44z** [comment]
This is the behaviour of the upstream library that is used for the email input. What is your expectation?

**Comment by pedro-nonfree** [comment]
as I already filled the form, it should accept it or reject it with a message such as "press enter for each email address introduced", but the most common UX regarding this is that after entering the email and making a space, it autoencloses that email in that square

**Comment by h44z** [comment]
if you use the TAB key after you entered you email it will be enclosed in a box and handled as valid email. I will check if it is possible to handle focus-loss on that field correctly

**Comment by h44z** [comment]
Fixed in the new release
