### ISSUE TITLE
Doc: Showing prominently config format for current stable version

### ISSUE THREAD

**Issue by Akira25** [h44z/wg-portal#286]
First of all: Really great software. We've deployed it in our university club and its just cool. Especially working great with our ldap deployment.

## Issue

We installed the current stable version of wg-portal (v1.0.19) and followed the guide on the config file shown here: https://github.com/h44z/wg-portal/blob/f1f5280cbcf6ee6c243e94a5423d3b38e87ec69c/config.yml.sample

We were not able to run the installation with this config file example, due to version incompabilities (the shown file seems to be made for the coming version two).

## Behaviour we aim for

With installing the current stable version (which is shown as current version) it would be really nice, to have an config file example, that is in the right format. It would be cool to have this pointed out in the docs somewhere.

We had to invest quite some time to dig into this issue. Nonetheless, really great software. Very much appreciated.

**Comment by Akira25** [comment]
It's right, that I am referencing to a v2 config. The problem I see is, that this config example is very prominent on the github page. As the current docs are quite spare on the right config file format, one naturally try to look into the github repo.

There will you find the version2 config file first, which does not work with the current stable version mentioned in the release section.

A possible solution might be, do amend the description of the config file format in the documentation on the website, or to make a clear note on the incompatible formats in e.g. the README.md.

This can lead to a much more smooth experience, when deploying wg-portal.

**Comment by h44z** [comment]
Thats why this hint is shown at the startpage of the Github repository:

**IMPORTANT**
Version 2 is currently under development and may contain bugs. It is currently not advised to use this version in production. Use version [v1](https://github.com/h44z/wg-portal/tree/stable) instead.

So use the config for V1, which is linked in the message.
