### ISSUE TITLE
Support for Gmail

### ISSUE THREAD

**Issue by valireality** [h44z/wg-portal#3]
Hi,
I love your work. This portal is excellent.

Can you, please, give a instructions how to setup email account from gmail?

Thank you.

**Comment by h44z** [comment]
To set up the email account that sends out the configuration emails you can use the following environment variables (found in [email.go](https://github.com/h44z/wg-portal/blob/master/internal/common/email.go#L13)):

 - EMAIL_HOST: smtp.gmail.com
 - EMAIL_PORT: 587
 - EMAIL_TLS: true
 - EMAIL_USERNAME: you@gmail.com
 - EMAIL_PASSWORD: your-gmail-pw or gmail-app-password

You can read the gmail documentation for how to setup gmail smtp server: https://support.google.com/a/answer/176600?hl=en#zippy=%2Cuse-the-gmail-smtp-server

**Comment by valireality** [comment]
Hi, thank you for your replay.

I configured wg-portal.env like this:
```
EMAIL_HOST=smtp.gmail.com
EMAIL_PORT=587
EMAIL_TLS=true
EMAIL_CERT_VALIDATION=no
EMAIL_USERNAME=xxx@gmail.com
EMAIL_PASSWORD=xxxxx
```

and i got this error when i try to send email:

```
500

Template error

template: email.html:103:80: executing "email.html" at <.Client.LdapUser>: can't evaluate field LdapUser in type server.Peer
```

**Comment by h44z** [comment]
I see, your configurations looks correct. There seems to be a bug in the mail template. I will fix this in the next version.

**Comment by valireality** [comment]
working great!
thanks :)
