### ISSUE TITLE
Endpoint not filled if client create

### ISSUE THREAD

**Issue by carstendigital** [h44z/wg-portal#30]
Hello I have the 1.09 version running.
The endpoint is correctly set in the configuration, but when a client logs in and a configuration is created the endpoint is empty.
Only when I then press Apply Global Settings without a change in the server configuration, all are always updated. 
The endpoint is then also entered for the missing ones. This was not the case before, it only updated the changed clients.

What can be the reason that when creating the endpoint is not set immediately?

**Comment by h44z** [comment]
Fixed in the new release
