### ISSUE TITLE
Add support for DNS in Server config (v1.0.19)

### ISSUE THREAD

**Issue by QuakeDragon** [h44z/wg-portal#338]
Wanted: The ability to add DNS settings to the server config. 
Breadcrumb: Admin login > Administration > Edit interface Settings > Server Mode > Server's Interface Configuration
I'd like to have "Server DNS" (or similar) as an option to fill in.
Why: In certain cases this allows clients to use short names instead of FQDNs.
Specifically for Active Directory environments where Domain Controllers provide private DNS.
Applies to v 1.0.19 - the version currently recommended for production environments. (Might be relevant to v2, not sure.)

Specifically, if we have the ability to add a line under the "Address" field of wg0.conf, like:
```
[Interface]
# Core settings
PrivateKey = QA+AB12cd34EfGHiJKLmnOPqr/st+u5VwxyzABCdeFg=
Address = 192.168.1.0/24
DNS = 192.168.1.2#dns02.thedomain.com,192.168.1.4#dns04.thedomain.com,192.168.1.6#dns06.thedomain.com
# Misc. settings (optional)
ListenPort = 51820
```
and in our Post Up we add `/etc/wireguard/update-dns-domain.sh` which contains the following:

```
#!/bin/bash
# Update DNS domain for wg0
resolvectl domain wg0 thedomain.com
```

then end-users can resolve "nslookup server" rather than having to use "nslookup server.thedomain.com"

As far as I can tell, Wireguard doesn't really have a domain directive - which is not surprising. This is why `resolvectl domain wg0 thedomain.com` needs to be ran after the interface comes up.

My current workaround, which is kind of dumb, uses a short bash script to check if the wg0.conf file has the DNS entries, and if not, adds them. I'm running this as a 5 minute cron job and it seems to work well enough. It also runs in Post Up, but that's probably not needed.
For anyone else who is looking for the workaround, it's something like this...
```
#!/bin/bash
##########
# File: /etc/wireguard/add-dns.sh
# This script checks the wg0.conf file to see if the DNS directive is present
# under the [Interface] key, then adds it if it is missing. Then it writes the
# modified conf file back over the original. Then for good measure, 
# we'll run the resolvectl domain wg0 thedomain.com
# In this manner we honor and preserve changes to peers and other settings made by wg-portal.
##########
# Temporary file to store the modified config
TEMP_FILE="/etc/wireguard/wg0_temp.conf"
# Check to see if the line already exists in the wg0.conf file.
if ! grep -q "192.168.1.2#dns02.thedomain.com,192.168.1.4#dns04.thedomain.com,192.168.1.6#dns06.thedomain.com" /etc/wireguard/wg0.conf; then
# Read the original wg0.conf and insert DNS entries after [Interface]
awk '
BEGIN { inserted=0 }
/^\[Interface\]$/ {
  print $0
  if (!inserted) {
    print "# DNS entries added by /etc/wireguard/add-dns.sh script"
    print "192.168.1.2#dns02.thedomain.com,192.168.1.4#dns04.thedomain.com,192.168.1.6#dns06.thedomain.com"
    inserted=1
  }
  next
}
{ print $0 }
' /etc/wireguard/wg0.conf > $TEMP_FILE
# Move the temporary file to replace the original wg0.conf
mv $TEMP_FILE /etc/wireguard/wg0.conf
# Just in case, run the resolvectl command to add the domain field to the wg0 device interface.
resolvectl domain wg0 thedomain.com
fi
```
I've tested this on three different versions of Active Directory running DNS (Server 2012 r2, Server 2019 and Server 2022) and this has worked every time. In my tests I've found this works with both Windows clients that are domain-joined and standalone (not joined to the AD domain.)
This is kind of similar to Issue #211 and #46 , but since this is a production environment, I stuck with the recommended 1.0.19.

**Comment by h44z** [comment]
This feature is already available in V2. New features for V1 are not planned at the moment.

![image](https://github.com/user-attachments/assets/b949cd23-d8ce-4db2-8956-bcab123902b6)
