### ISSUE TITLE
Https for wg-portal

### ISSUE THREAD

**Issue by ItterVH** [h44z/wg-portal#34]
Hi all.
Has anyone  to combine in docker nginx and wg-portal to work on https? I ran into the fact that due to **network_mode: "host"** the nginx in the container cannot get to the portal via the internal network. And if I do upstream through the white IP of the host, the port with http must remain open to the Internet and this is undesirable in my case.
Thanks in advance for the answers

**Comment by h44z** [comment]
If you change the config option LISTENING_ADDRESS from :8123 to 127.0.0.1:8123, the wg-portal server is no longer reachable from the public.

**Comment by ItterVH** [comment]
Thanks! It works.
