### ISSUE TITLE
Missing security attributes when generating session cookies

### ISSUE THREAD

**Issue by bstnbuck** [h44z/wg-portal#39]
Hi, 
in my opinion, the WG-Portal is the best solution so far for managing Wireguard in enterprise networks with LDAP/AD connection. In addition, some features are solved very performant. Great work!
The cookies that WG-Portal creates, on the other hand, need a better implementation. From a security point of view, they are not secured against possible XSS attacks (cross-site scripting) and against insecure http connections. The attribute "Secure" and "HttpOnly" therfore must be added.

To add this attributes to the cookies the following line of code at `/internal/server/server.go` must be replaced by the following part or something like this:

replace line `119`:
```go
s.server.Use(sessions.Sessions("authsession", memstore.NewStore([]byte(s.config.Core.SessionSecret))))
```
with something like this:
```go
store := memstore.NewStore([]byte(s.config.Core.SessionSecret))
store.Options(sessions.Options{
	Path: "/",
	MaxAge: 86400, // 1 Day
	Secure: true,
	HttpOnly: true,
})
s.server.Use(sessions.Sessions("authsession", store))
```

**Comment by h44z** [comment]
@bstnbuck Activating the "Secure"  flag only makes sense if WG-Portal is used behind an SSL proxy right?

**Comment by bstnbuck** [comment]
@h44z Yes that is true. But I think that this is mostly the case. Maybe you could create a configuration option for this, which sets this accordingly?

**Comment by h44z** [comment]
This issue should be fixed now. The "Secure" flag is set if the EXTERNAL_URL config option starts with "https".

**Comment by bstnbuck** [comment]
Great work!
