### ISSUE TITLE
Import existing wiregurad configurations 

### ISSUE THREAD

**Issue by cilcil97** [h44z/wg-portal#4]
I have an issue when I import users with an existing wireguard configuration  it does not load the private key in the configuration and when you try to export the configuration the private key is missing.

**Comment by h44z** [comment]
This is intentional as WireGuard does not save the private keys of the configured peers. If you have the private keys noted somewhere, you can set the environment variable EDITABLE_KEYS to true in order to edit the private key and the shared secret of the imported peers.

**Comment by cilcil97** [comment]
Thank you very much!
