### ISSUE TITLE
Deleting or modifying user 

### ISSUE THREAD

**Issue by chibomorto** [h44z/wg-portal#40]
Thank you for your great work! Got wg-portal to work and I really appreciate the way it handles server and client configurations, including Post-up and Post-down. The only thing I can´t find is a way to delete users from the user management tab. I also can’t change user name or remove administration privileges. When I save the changes made to the user I get a success message but it all keeps the same.

**Comment by bilbolodz** [comment]
Is these patch included in current stable (v1) version of portal? I've installed portal using docker (stable image) and can' see it.
