### ISSUE TITLE
failed to open config file config.yml Warning

### ISSUE THREAD

**Issue by chibomorto** [h44z/wg-portal#44]
Thank You again for the great job creating wg-portal. 
I’m running wg-portal on ubuntu 20.04, in a docker stack with several apps installed with docker compose. All containers are being update automatically with Watchtower (daily scheduled at 4:00 am).
Found two new issues:
First: Although wg-portal is working, despite of the issues #40, #41 and #42, the client configuration download button is not working; to download the client .conf file, I had to press the right mouse button and choose, “open link in a new tab”.

Second: Wg-portal log shows a warning after Watchtower updated the container last night:

INFO[2021-09-13 04:00:29] starting WireGuard Portal Server [master-9147fe3]... ,
INFO[2021-09-13 04:00:29] real working directory: /app ,
INFO[2021-09-13 04:00:29] current working directory: . ,
**### WARN[2021-09-13 04:00:29] unable to load config.yml file: failed to open config file config.yml: open config.yml: no such file or directory, using default configuration... ,**
INFO[2021-09-13 04:00:29] setup of service completed! ,
INFO[2021-09-13 04:00:29] starting web service on :8123 ,

Could it be a folder permissions issue? My docker-compose is setting WG_CONFIG_PATH to /etc/wireguard wich is a root acess folder. No config.yml is beyng created on that folder. Do I need to change this path to another folder where wg-portal as write permissions.

Sorry for the basic beginner questions.

**Comment by h44z** [comment]
Regarding the download issue, i can not reproduce this on chrome, which browser are you using?

And the warning can be ignored (I am gonna remove it in a future release) as you configure wg-portal via environment variables and not via config file.

**Comment by chibomorto** [comment]
Thank you for your answer.
I’m using Edge (Chromium) on my PC, and Chrome for android on my smartphone
Experiencing the issue on both.
Initially I had no problem downloading the .conf file.

**Comment by chibomorto** [comment]
Ok. Found the answer. I was using wg-portal inside a iframe tab from Organizrr. If I i open it directly on the browser, download button works as expected. Is there a way to make work inside the i-frame?

**Comment by h44z** [comment]
Can you check the chrome developer tools (ctrl + i) and see if there are any errors or warnings after you clicked the download button?

**Comment by chibomorto** [comment]
No right now, but i will check it later and repport back.

**Comment by chibomorto** [comment]
Ok. I believe this is the error:
"Download is disallowed. The frame initiating or instantiating the download is sandboxed, but the flag ‘allow-downloads’ is not set. See https://www.chromestatus.com/feature/5706745674465280 for more details."

**Comment by h44z** [comment]
There is nothing wg-portal can do. You have to change the iframe parameters, see https://html.spec.whatwg.org/multipage/iframe-embed-object.html#attr-iframe-sandbox
