### ISSUE TITLE
Client config not updated when server config changes

### ISSUE THREAD

**Issue by tedr56** [h44z/wg-portal#45]
Hi. I finally got my setup working.
Thanks for the work btw.

I mistakenly entered my external domain wrong. When I changed it to the right one I noticed the client config was keeping the domain from creation.

**Comment by h44z** [comment]
You have to change the public endpoint address in the interface configuration, save it, and then apply it to all clients.

**Comment by tedr56** [comment]
Ho, I missed that one on my mobile screen.
Thank you very much.
