### ISSUE TITLE
Using the LDAP  uid Attribute as login name

### ISSUE THREAD

**Issue by flischi** [h44z/wg-portal#50]
I'm trying to use another LDAP Attribute than the email address as the login name. I tried  attrEmail: uid (or cn) to override the default, but no luck. Also the Filter loginFilter: (&(objectClass=organizationalPerson)(uid={{login_identifier}}) didn't help.

**Comment by h44z** [comment]
Are you using the yaml config file or environment variables for configuration?

**Comment by flischi** [comment]
I'm using the yaml file at the moment  but the .env file beforehand. Sadly no difference. In the .env file we had LDAP_ATTR_EMAIL=cn

**Comment by h44z** [comment]
Set the log level to trace, the log messages are written to stdout. Login filter should work, see #36 or #19.
Maybe you can find something in the logs.

**Comment by flischi** [comment]
LDAP_SYNC_FILTER=(objectclass=inetOrgPerson) did the Trick! Thanks for the quick response, great Project :-)
