### ISSUE TITLE
Wg0 not fully configured

### ISSUE THREAD

**Issue by danielbeicht** [h44z/wg-portal#51]
Hi,
I'm new to Wireguard and trying to get wg-portal running. The connection to my ldap works fine, however when I try to login I get the message "Warning: WireGuard Interface wg0 is not fully configured! Configurations may be incomplete and non functional!"

My wg0 is up using this wg0.conf
[Interface]
Address = 10.52.3.1/24
SaveConfig = true
ListenPort = 51820
PrivateKey = private_key_here

Can you tell me what I'm missing?
Thanks in advance!

**Comment by dada513** [comment]
how did you fix it?

**Comment by pbolle** [comment]
I have the same problem. Any idea how to solve this?

**Comment by h44z** [comment]
Server Interface needs:
 - PublicKey != ""
 - len(IPAddresses) > 0
 - d.DefaultEndpoint != ""

Client Interface needs:
 - PublicKey != ""
 - len(IPAddresses) > 0

**Comment by HolgerHees** [comment]
I had the same problem. I followed the described setup and configuration from README.md including LDAP configuration with the result that I got the same message.

I was able to start to start docker-compose
I was able to login with my LDAP credentials in the web ui
But I saw the message on top.

The missing part was, that you have to open the wireguard administration page and fill the option "Public Endpoint for Clients".

Maybe this should be mentioned in README.md too.

**Comment by jasonwee** [comment]
> The missing part was, that you have to open the wireguard administration page and fill the option "Public Endpoint for Clients".

can you clarify where is that exactly? perhaps with screenshot is much better... get the same error 

my sample wg0.conf
```
[Interface]
Address = 10.0.0.1/24
SaveConfig = true
PostUp = iptables -A FORWARD -i wg0 -j ACCEPT; iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE; ip6tables -A FORWARD -i wg0 -j ACCEPT; ip6tables -t nat -A POSTROUTING -o eth0 -j MASQUERADE
PostDown = iptables -D FORWARD -i wg0 -j ACCEPT; iptables -t nat -D POSTROUTING -o eth0 -j MASQUERADE; ip6tables -D FORWARD -i wg0 -j ACCEPT; ip6tables -t nat -D POSTROUTING -o eth0 -j MASQUERADE
ListenPort = 51820
PrivateKey = server_private_key

[Peer]
PublicKey = client_public_key
AllowedIPs = 10.0.0.2/32
```
