### ISSUE TITLE
Documentation for configuration values

### ISSUE THREAD

**Issue by h44z** [h44z/wg-portal#6]
Add a documentation section for all configuration values (yaml and environment) to README.

Currently all possibly options have to be searched in:

 - [Mail settings](https://github.com/h44z/wg-portal/blob/master/internal/common/email.go#L13)
 - [WireGuard settings](https://github.com/h44z/wg-portal/blob/master/internal/wireguard/config.go#L5)
 - [LDAP settings](https://github.com/h44z/wg-portal/blob/master/internal/ldap/config.go#L10)
 - [Database settings](https://github.com/h44z/wg-portal/blob/master/internal/common/db.go#L24)
 - [Core settings](https://github.com/h44z/wg-portal/blob/master/internal/server/configuration.go#L56)

**Comment by umka-beaf** [comment]
Hi.
Maybe you could give us `config.yml` example file. It's difficult to me to combine it from go code...
Thank you for your app.

**Comment by h44z** [comment]
I have added a table with all configuration values and brief descriptions as well as a sample yaml configuration to the README.
Is this sufficient for you @umka-beaf?

**Comment by umka-beaf** [comment]
> I have added a table with all configuration values and brief descriptions as well as a sample yaml configuration to the README.
> Is this sufficient for you @umka-beaf?

That's great! Thanks for so quick response. I'll try to make some "large" compose file with mysql and wireguard docker for quick and clear install to non virtual host...
Your app is very helpfull. :)
