### ISSUE TITLE
Libc6 Version Error

### ISSUE THREAD

**Issue by valireality** [h44z/wg-portal#61]
Last version 1.0.12 was compiled with libc_2.28, but Ubuntu 18.04 is using 2.27
```./wg-portal-amd64: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by ./wg-portal-amd64)```

Can it be compiled with version 2.27?

Thanks

**Comment by h44z** [comment]
The newest release (1.0.13) contains *-legacy binaries build with GLIBC 2.24. Those binaries should work for Ubuntu 18.04 as well.
