### ISSUE TITLE
Options to insert Custom Css or Enable disable the Frontpage Cards

### ISSUE THREAD

**Issue by lenusch** [h44z/wg-portal#65]
Hi,

can you kindly add some CSS URL for docker image or possibility to control more GUI.
i.e. disable some of the cards / boxes on the Frontpage. All the links to wireguard.

**Comment by h44z** [comment]
Hi,
for this you have to change the HTML template manually. After changing the template (assets/tpl/index.html) you have to recompile wgportal.
