### ISSUE TITLE
JumpCloud LDAP compatibility question

### ISSUE THREAD

**Issue by Dmitry1987** [h44z/wg-portal#67]
Hello, first of all thanks for the great effort to develop this portal. 
I am trying to connect it with a JumpCloud LDAP which is a standard LDAP nothing special, and I expected it to just work, but after trying all syntax combinations in the user DN, base DN, and admin group DN, I keep getting this error in log when I start the portal:

```
wg-portal    | WARN[2021-11-03 05:35:47] failed to setup LDAP connection, LDAP features disabled 
wg-portal    | ERRO[2021-11-03 05:35:47] skipping provider registration: unable to open ldap connection: LDAP Result Code 34 "Invalid DN Syntax": invalid DN 
```

My LDAP settings are:

```
...
      - LDAP_ENABLED=true
      - LDAP_URL=ldap://ldap.jumpcloud.com:389
      - LDAP_STARTTLS=true
      - LDAP_BASEDN="o=123123123123,dc=jumpcloud,dc=com"
      - LDAP_USER="devops@domain.com"
      - LDAP_PASSWORD="xxxxx"
      - LDAP_ADMIN_GROUP="cn=VPN Admin,ou=Users,o=123123123123,dc=jumpcloud,dc=com"
      - LOG_LEVEL=trace
```
And I tried variations of this
```
      - LDAP_BASEDN="dc=jumpcloud,dc=com"
      - LDAP_USER="123123123123\\devops@domain.com"
```
and also full user name including base DN, same effect.

Did anyone make it work with JumpCloud, or is there an obvious mistake I don't see in my config?

**Comment by Dmitry1987** [comment]
I also tried this following the example from JumpCloud docs, and it should work, but for some reason it doesn't
```
      - LDAP_BASEDN="ou=Users,o=123123123123,dc=jumpcloud,dc=com"
      - LDAP_USER="uid=system,ou=Users,o=123123123123,dc=jumpcloud,dc=com"
```
for cli "ldapsearch" the above works to retrieve information of users for example, like this
`ldapsearch -H ldap://ldap.jumpcloud.com:389 -ZZ -x -b "ou=Users,o=YOUR_ORG_ID,dc=jumpcloud,dc=com" -D "uid=LDAP_BINDING_USER,ou=Users,o=YOUR_ORG_ID,dc=jumpcloud,dc=com" -W "(objectClass=inetOrgPerson)"`

the user I am trying to use is:
```
# system, Users, 123123123123, jumpcloud.com
dn: uid=system,ou=Users,o=123123123123,dc=jumpcloud,dc=com
uidNumber: 5003
gidNumber: 5003
loginShell: /bin/bash
givenName: system
jcLdapAdmin: TRUE
objectClass: top
objectClass: person
objectClass: organizationalPerson
objectClass: inetOrgPerson
objectClass: shadowAccount
objectClass: posixAccount
objectClass: jumpcloudUser
uid: system
homeDirectory: /home/system
mail: devops@domain.com
userPassword: xxxxx
sn: devops
cn: system devops
memberOf: cn=VPN Admin,ou=Users,o=123123123123,dc=jumpcloud,dc=com
```

**Comment by h44z** [comment]
Can you test with the latest master build? I added a more verbose message to the ldap error logs, so that we can narrow down the problem.

**Comment by Dmitry1987** [comment]
Will try now, thanks

**Comment by Dmitry1987** [comment]
```
wg-portal    | WARN[2021-11-08 12:27:31] failed to setup LDAP connection, LDAP features disabled 
wg-portal    | ERRO[2021-11-08 12:27:31] skipping provider registration: unable to open ldap connection: failed to bind user: LDAP Result Code 34 "Invalid DN Syntax": invalid DN 
```

A bit more detailed, but the password works, I am setting up pfSense with same user and it works for now, with LDAP. I'm trying to make OpenVPN auth in LDAP there and seems to be good for now. So the password in this case is 100% correct, and the user too. Maybe it expects the user to be in full path format?

**Comment by Dmitry1987** [comment]
I tried this too `LDAP_LOGIN_FILTER="&(objectClass=inetOrgPerson)(uid={{login_identifier}})"`  based on LDAP integration of pfSense that worked (https://www.reddit.com/r/PFSENSE/comments/lshbi1/importing_a_server_certificate_for_jumpcloud/)
and called the LDAP_USER=system  (because it's uid is system, and uid is the user in jumpcloud)

**Comment by h44z** [comment]
maybe it is due to the quotes (")?

try to specifiy all environment variables without quotes.

So for example:

`LDAP_LOGIN_FILTER=&(objectClass=inetOrgPerson)(uid={{login_identifier}})`

gets

`LDAP_LOGIN_FILTER=&(objectClass=inetOrgPerson)(uid={{login_identifier}})`

**Comment by Dmitry1987** [comment]
nope, doesn't help. strange 🤔

**Comment by h44z** [comment]
hm, I am gonna setup a jumpcloud account to test this out...

**Comment by Dmitry1987** [comment]
Thank you, that's an interesting case indeed, I verified all fields one more time and can't see anything that could be wrong.

**Comment by h44z** [comment]
Ok, it seems you have some kind of configuration error. I created a new JumpCloud Ldap account and it works flawlessly:

This is the wg-portal configuration I am using (in yaml format):
```yaml
core:
  ldapEnabled: true
ldap:
  url: ldap://ldap.jumpcloud.com:389
  dn: ou=Users,o=618d8fXXXXXXXXXX,dc=jumpcloud,dc=com
  startTLS: true
  user: uid=wgportal,ou=Users,o=618d8fXXXXXXXXXX,dc=jumpcloud,dc=com
  pass: Test123!
  adminGroup: cn=admins,ou=Users,o=618d8fXXXXXXXXXX,dc=jumpcloud,dc=com
  syncFilter: (objectClass=inetOrgPerson)
```

You have to adjust adminGroup, syncFilter, loginFilter to fit your needs of course, but JumpCloud LDAP works =)

And this is the admin user in JumpCloud:
![image](https://user-images.githubusercontent.com/1370804/141376542-91fac3d9-de97-4ef9-b2d0-72dc4350b9a7.png)

**Comment by Dmitry1987** [comment]
Sounds good, maybe it's because I use environment variables and not the
file, I'll format it into the file and will try again.

**Comment by Dmitry1987** [comment]
Oh it works now, I think the mistake was in not using the correct format for "syncFilter", everything else seems the same (I tried with a config file now, and not the env vars. But I suspect the filter to be the reason, it was different in my attempts to launch it).
