### ISSUE TITLE
Use server-name as name for downloads / configuration

### ISSUE THREAD

**Issue by EugenMayer** [h44z/wg-portal#68]
Yet the name in the exported configuration corresponds to the name given in the API.

So if i create 'bob' it will be named bob, so the client interface is bob and also the VPN UI will show bob on the client.
Same goes for Lisa and so on.

This does not make a lot of sense, since Lisa and Bob do not connect to Lisa or Bob, they connect to a specific server and that is what it should tell them.

Creating 'myserver' in the UI as name does not make sense either, since one would end up having dozens of 'myserver' entries.

Is there any chance to convince you to use the server-name as the name (maybe also sanitized replacing spaces with `_` and so one)? Would be great

**Comment by valireality** [comment]
i think this will go in v2 as a future related to this one:
https://github.com/h44z/wg-portal/issues/62#issue-1027142781

**Comment by h44z** [comment]
I'm not sure if I understand your request correctly. You want to change the filename of the downloaded config file?
