### ISSUE TITLE
check ldap user if exist

### ISSUE THREAD

**Issue by fettfoen** [h44z/wg-portal#70]
thanks for your great job, really!

there is one question for me. does the portal check if user are gone from ldap and purge them from mysql database and give free the ip/config what was created?

for example i have 10000 users synced successfully. but after time serveral users are leaving and were deleted from our active directory permamently. 

do i need check/delete manually or is there some routin that doing this? if not this would be a very important and helpful "enterprise" feature.

keep it up & br

ff

**Comment by h44z** [comment]
wg-portal checks if the user is missing or disabled (via ldap filter LDAP_SYNC_FILTER) in ldap, if so, the portal user will be disabled as well which means that all associated peers for the user get disabled (not deleted)

**Comment by nightincode** [comment]
How often are the checks preformed? I'm looking at the same thing

**Comment by h44z** [comment]
@nightincode the sync interval is one minute
