### ISSUE TITLE
Disable user active until wg-restart

### ISSUE THREAD

**Issue by moel13** [h44z/wg-portal#71]
Thank you for this service.

There is a problem that After a user has been disabled, its peer delete from wg0.conf but can connect until "wg-quick down wg0" and "wg-quick up wg0"
But when enable user again, the config return to wg0.conf and it can connect without restart !!!

**Comment by zyxep** [comment]
@h44z will this be fixed in v2? 👀

**Comment by h44z** [comment]
yes

**Comment by h44z** [comment]
just tested this, peers get deactivated as expected. also currently connected peers lose the connection
