### ISSUE TITLE
Customize Peer Interface

### ISSUE THREAD

**Issue by longnv107** [h44z/wg-portal#73]
Request New Feature.
We can change the key public key with the network traffic . If you can be select the fields to display. that's great
![image](https://user-images.githubusercontent.com/76582852/143527753-b67ca2ce-c5f6-4447-85b5-c42ead63429b.png)

It's a great project.
Thanks so much.

**Comment by h44z** [comment]
Customizing the UI is currently not supported. But you can change the HTML template and re-compile the project yourself...
