### ISSUE TITLE
Portal creates Configurations with wrong Keys

### ISSUE THREAD

**Issue by banshee091** [h44z/wg-portal#74]
Hey there,
I set up a server with two different wan interfaces and two wireguard interfaces with different keypairs.
From the routing perspective everything works just fine and as intended. 
But if I try to create user configs on the portal, the local config file always has the public key of the first wireguard interface.
The preview seems correct and the QR-Code is working just fine, but the downloaded file contains the wrong public key for the server-peer.
Edit: The portal was built on a local machine and is running inside a VM without using docker. 
EDIT2: IMPORTANT: This only happens for "normal" users, admin users will get the correct public-key.
Simplified:

-- | wg0 | wg1
--|-----|-----
public-key | ABC | 123
key shown in wg-portal admin view | ABC | 123
key in database | ABC | 123
key imported via qr-code | ABC | 123
key in downloaded config file | ABC | **ABC**

Any ideas why this is happening?
Thank you very much for this awesome Project!

**Comment by h44z** [comment]
Thats a bug, I will fix it asap

**Comment by banshee091** [comment]
Awesome! Thanks!

**Comment by h44z** [comment]
Should be fixed.

I'm gonna check the other issues and will create a new release in the next few days =)
