### ISSUE TITLE
Integration with prometheus_wireguard_exporter friendly name

### ISSUE THREAD

**Issue by ultram4rine** [h44z/wg-portal#76]
New feature request

Add integration with [prometheus_wireguard_exporter friendly name](https://github.com/MindFlavor/prometheus_wireguard_exporter#friendly-tags).

As i understood the only thing to do is add `# friendly_name = {{ .Identifier }}` to [peer in interface template](https://github.com/h44z/wg-portal/blob/master/internal/wireguard/tpl/interface.tpl#L58).

If that's all, then i have PR ready, but that's to easy, maybe add this as option to configuration?

**Comment by vivek030** [comment]
Totally agree, this feature is important !!!

**Comment by vivek030** [comment]
Hi,
There is bug while testing for prometheus_wireguard_exporter friendly name.
# friendly_name  or frindly_json , when you update comment in wg-portal generated config file, promethus wireguard update data for previous peer.  Currently wg-portal manages comments like this:

# AUTOGENERATED FILE - PROVIDED BY WIREGUARD PORTAL
# WireGuard configuration: **************
# -WGP- PublicKey: ****************
[peer]

But promethus wireguard expects data below [peer] section :
[peer]
# friendly_name =
# friendly_json =

**Comment by ultram4rine** [comment]
@vivek030 i hanve implemented this [here](https://github.com/ultram4rine/wg-portal/tree/wireguard-exporter-friendly-tags), you need to add `WG_EXPORTER_FRIENDLY_NAMES=true` to env config or `wgExporterFriendlyNames: true` to yml config.
