### ISSUE TITLE
All in one docker container with Wiregaurd Controller + WG UI

### ISSUE THREAD

**Issue by drtech981** [h44z/wg-portal#83]
Would be nice to have a single docker container with both the Wiregaurd Server + WG Portal so it becomes a nice and easy package to deploy (something like https://github.com/WeeJeWel/wg-easy)

Thanks for this awesome project btw ❤️, you have solved one of my biggest hurdles towards adopting Wiregaurd in place or openvpn access server!

**Comment by h44z** [comment]
not planned for now
