### ISSUE TITLE
"host" network_mode is incompatible with port_bindings

### ISSUE THREAD

**Issue by MaverickTN** [h44z/wg-portal#84]
After a few updates to my setup over the past few months and a return to add a new host showed me this when trying to start the docker container.

"host" network_mode is incompatible with port_bindings

Any suggestions?

Using

Docker version 20.10.7, build 20.10.7-0ubuntu5.1
docker-compose version 1.27.4, build unknown

docker-compose.yml
version: '3.6'
services:
  wg-portal:
    image: h44z/wg-portal:master
    container_name: wg-portal
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    network_mode: "host"
    volumes:
      - /etc/wireguard:/etc/wireguard
      - ./data:/app/data
    ports:
      - '192.168.2.1:8123:8123'
    environment:
      - WG_DEVICES=wg0,wg1,wg2,wg3,wg4
      - WG_DEFAULT_DEVICE=wg0
      - WG_CONFIG_PATH=/etc/wireguard
      - EXTERNAL_URL=http://url.tld
      - WEBSITE_TITLE=WireGuard VPN
      - COMPANY_NAME=Company
      - ADMIN_USER=email@domain.com
      - ADMIN_PASS=Password

**Comment by thechubbypanda** [comment]
If you're running in host mode, you can't map ports because the ports are already on the host.  You can safely remove the ports section and it should work.

**Comment by philippderdiedas** [comment]
Close the issue, it's a docker / user error
