### ISSUE TITLE
LDAP_USER_GROUP/usersGroup

### ISSUE THREAD

**Issue by valireality** [h44z/wg-portal#86]
Hello,

can this option be implemented, to sync users from ldap groupe, for example, if the users are in 'wiregurd-users' group, then only them to be sync in the portal?
Just like the LDAP_ADMIN_GROUP/adminGroup.

Thank you

**Comment by zyxep** [comment]
use the setting `LDAP_ATTR_GROUPS`

**Comment by h44z** [comment]
you can use the configuration attribute **LDAP_SYNC_FILTER** to only sync specific ldap users.
