### ISSUE TITLE
LDAP_LOGIN_FILTER vs LDAP_SYNC_FILTER

### ISSUE THREAD

**Issue by drtech981** [h44z/wg-portal#88]
Can someone explain to me what these two variables exactly do ?

I am trying to get a user to login using their userPrincipalName, I made the change 

`(&(objectClass=organizationalPerson)(userPrincipalName={{login_identifier}})(!userAccountControl:1.2.840.113556.1.4.803:=2))`

however, it is still not working.

**Comment by h44z** [comment]
Ldap entries that match the sync filter will be created as users in the user database (including firstname, lastname and so on). This user entries will then be kept in sync with the ldap server.
The login filter on the other hand specifies which users are allowed to authenticate against ldap.
This was implement to allow scenarios where many ldap users should show up in wg-portal, but only a few of them (admins for example) should be allowed to log in.


Your login filter looks good to me, maybe the user account control constraint is wrong?

**Comment by bee7ch7** [comment]
> 

How often wg-portal syncing with ldap ?
If I understood well, when the user with active profile in wg-portal will be deactivated in ldap, it should be synced and deactivate profile?

**Comment by h44z** [comment]
The sync interval is 1 minute (https://github.com/h44z/wg-portal/blob/master/internal/server/ldapsync.go#L21).

You understood that correctly, if a user in ldap gets deactivated, the change is reflected to wgportal and the user with peers is deactivated. 
The process is reversed once the user gets activated in ldap again.
