### ISSUE TITLE
Allow the Configuration of Interface Configuration Hooks via Multiple Lines

### ISSUE THREAD

**Issue by TheFrozenDuck** [h44z/wg-portal#89]
Sometimes the configuration hooks can get rather long for a single line, e.g., when configuring IPv4 and IPv6 at the same time.

It would be neat if each command could be added in its own line.

I would imagine something like this:

![image](https://user-images.githubusercontent.com/5834688/152685321-b0685538-ee47-47cd-8ef7-9b497cec876f.png)

or this:

![image](https://user-images.githubusercontent.com/5834688/152685425-956f5ca4-3f28-4666-b387-1d9460f048c0.png)

**Comment by h44z** [comment]
this is now possible in v2
