### ISSUE TITLE
Only able to connect first peer 

### ISSUE THREAD

**Issue by vivek030** [h44z/wg-portal#9]
Thanks for the great project !!!

I am able to connect to only first peer, as soon as i add second or third peer, first peer gets disconnected(cant ping wg server ip).
Am i missing something or is this a bug?

**Comment by h44z** [comment]
Can you describe your setup in a bit more detail? (Server-Mode/Client-Mode, Docker/Raspberry/Other, OS, Version...)

Maybe you can also download the interface configuration file and post it here, but make sure to remove sensitive information like private keys, ip addresses and so on!

**Comment by vivek030** [comment]
Hi,
I think i figured out the issue, when i clicked interface advance settings, enabled Save Configuration options this problem started.
i restarted wg interface manually and things started working.

Note - Save Configuration option always defaults to disabled even if i enable that option.

**Comment by h44z** [comment]
Oh, I think you misunderstood the "Save Configuration" option. 

To cite it from the wg-quick manual:

> SaveConfig — if set to `true', the configuration is saved from the current state of the interface upon shutdown. Any changes made to the configuration file before the interface is removed  will therefore be overwritten.

This option does not really make sense when using the WireGuard Portal, it is just there to have full control over all WireGuard options. But for a normal use case you should keep it disabled.

**Comment by vivek030** [comment]
Thanks... Closing the issue..
