### ISSUE TITLE
LDAP sync and login multiple errors

### ISSUE THREAD

**Issue by thechubbypanda** [h44z/wg-portal#90]
Heyooo

Firstly, love the work that's gone into this, thanks.

I'm having a slight issue with LDAP sync.

Here's my config:

```
LDAP_ENABLED: "true"
LDAP_URL: ldap://localhost:389
LDAP_BASEDN: OU=users,DC=example,DC=uk
LDAP_USER: CN=readonly,DC=example,DC=uk
LDAP_PASSWORD: XXXXXXXXXXXXXXXXXXXX
LDAP_ADMIN_GROUP: CN=wheel,OU=groups,DC=example,DC=uk
LDAP_LOGIN_FILTER: "(&(objectClass=person)(uid={{login_identifier}}))"
LDAP_SYNC_FILTER: "(objectClass=person)"
LDAP_STARTTLS: "false"
```

### Whenever I try to login, I get:
> CSRF token mismatch

The logs from wg-portal in this case are just get and post requests at WARN level

### Whenever the sync happens, these are the logs:  
wg-portal
```
TRAC[2022-02-26 15:02:37] syncing ldap users to database...
ERRO[2022-02-26 15:02:37] failed to fetch users from ldap: failed to search in ldap: LDAP Result Code 32 "No Such Object":
```
ldap
```
621a431b conn=1306 fd=12 ACCEPT from IP=172.20.0.1:39766 (IP=0.0.0.0:389)
621a431b conn=1306 op=0 BIND dn="cn=readonly,dc=example,dc=uk" method=128
621a431b conn=1306 op=0 BIND dn="cn=readonly,dc=example,dc=uk" mech=SIMPLE ssf=0
621a431b conn=1306 op=0 RESULT tag=97 err=0 text=
621a431b conn=1306 op=1 SRCH base="ou=users,dc=example,dc=uk" scope=2 deref=0 filter="(objectClass=person)"
621a431b conn=1306 op=1 SRCH attr=dn mail mail givenName sn telephoneNumber memberOf
621a431b conn=1306 op=1 SEARCH RESULT tag=101 err=32 nentries=0 text=
621a431b conn=1306 fd=12 closed (connection lost)
```

I noticed that it's always asking for telephone number which doesn't exist for my users. Is there a way to change this?

The ldap setup I'm using is `osixia/openldap:latest` with `wheelybird/ldap-user-manager:latest`

Hope y'all can help me out :)

**Comment by h44z** [comment]
The csrf token error can be fixed if the external url config property is set correctly.

Regarding the ldap error: you can try to override the phone number field and use a fieldname that exists in your ldap schema. Or simply add a phone number field to the schema.
