### ISSUE TITLE
How can I use a certificate against a LDAP server ?

### ISSUE THREAD

**Issue by the-so6** [h44z/wg-portal#91]
Hi,

We are trying to configure Gsuite LDAP in wg-portal. Google give us certificate and key to connect with their LDAP servers.
We do not find the documentation to give the rights parameters.

That We try :
```
LDAP_ENABLED: "true"
LDAP_URL: "ldaps://ldap.google.com:636"
LDAP_STARTTLS: "false"
LDAP_BASEDN: "cn=xxx,ou=Groups,dc=xxx,dc=com"
LDAPTLS_CERT: "/app/cert/Google.crt"
LDAPTLS_KEY: "/app/cert/Google.key"
```

with this configuration, we got that error:

```
ERRO[2022-03-10 09:21:06] skipping provider registration: unable to open ldap connection: failed to bind user: LDAP Result Code 49 "Invalid Credentials": Incorrect password
```

When we tried with `ldapsearch` it is working well with these env variables:

```
LDAPTLS_CERT=./cert/Google.crt
LDAPTLS_KEY=./cert/Google.key
LDAPTLS_CIPHER_SUITE=NORMAL:!VERS-TLS1.3
```

Thanks for your help

**Comment by h44z** [comment]
Ldap certificate authentication implemented, thanks to @the-so6 !
