### ISSUE TITLE
Cant delete autodetected peer

### ISSUE THREAD

**Issue by wisdomdevil** [h44z/wg-portal#93]
Hola. After install wg-portal detected peer, but now i delete it from config, but user still in UI.
Steps:
1) docker-compose down
2) wg-quick down wg0
3) editing /etc/wireguard/wg0.conf
4) wg-quick up wg0
5)docker-compose up -d

But user still showing in UI

![image](https://user-images.githubusercontent.com/74432905/160231227-93b8b756-f217-4321-99a2-7ae41fbe7fe3.png)

(i disabled it)

How can i totally remove them ?

**Comment by KMakarevych** [comment]
You need to delete user from sqlite database.
```
sqlite3 wgportal_folder/data/wg_portal.db
```
```
delete * from peers where identifier = 'some_data';
```

**Comment by h44z** [comment]
Simply delete it in the UI?

![image](https://user-images.githubusercontent.com/1370804/198128788-515e2ee4-4c5b-4055-8995-62363e725048.png)
