### ISSUE TITLE
Configuration file name is too long.

### ISSUE THREAD

**Issue by commonism** [h44z/wg-portal#94]
The configuration file name is created using the username and profile name.

https://github.com/h44z/wg-portal/blob/83271b5d347d088e1fc27dceb121874834544933/internal/server/handlers_peer.go#L231-L248

https://github.com/h44z/wg-portal/blob/83271b5d347d088e1fc27dceb121874834544933/internal/wireguard/peermanager.go#L226-L229

The resulting name 'can' be longer than 15 characters, [which is the IFNAMSIZ limit for interfacenames on linux](https://github.com/spotify/linux/blob/master/include/linux/if.h#L26) .

The wg error message is not that helpful, users are unhappy ([related](https://github.com/StreisandEffect/streisand/issues/1350)).

I propose to use an identical configuration file name for all users which is imited to IFNAMESIZE.

**Comment by h44z** [comment]
v2 limits the configuration file name - import problems should no longer occur
