### ISSUE TITLE
Admin area image loading

### ISSUE THREAD

**Issue by nightincode** [h44z/wg-portal#96]
Thanks for this amazing portal. Using it for a medium sized organization. We have 500 users. With every one having 1 or 2 profiles the number of profiles are around 1500 on one server. The portal tries to load all the QR codes while loading the administration page which basically makes it commit suicide.

Can this bug be addressed? I don't think its warranted to load all QR codes on page load in the admin area.

**Comment by h44z** [comment]
I am currently rewriting the UI using VueJS, I will consider paging entries and lazy loading  =)

**Comment by nightincode** [comment]
Time spent: 0:00

**Comment by nightincode** [comment]
Time spent: 0:00

**Comment by h44z** [comment]
I have implemented a quick-fix for v1 which uses browser based lazy loading of images (only newer browsers support this though: https://developer.mozilla.org/en-US/docs/Web/Performance/Lazy_loading#browser_compatibility)
